name: CI

on:
    push:
        branches: [ "main" ]
        tags: [ "**" ]
    pull_request:
        branches: [ "main" ]

env:
    BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[startsWith(github.ref, 'refs/tags/')] }}
    BUILD_DOTNET_VERSION: 6.0.x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup .NET
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --configuration $BUILD_CONFIGURATION --no-restore
            -   name: Test
                run: dotnet test --configuration $BUILD_CONFIGURATION --no-build --verbosity normal
            -   name: Pack
                run: dotnet pack --configuration $$BUILD_CONFIGURATION --no-build
            -   name: Upload build output
                uses: actions/upload-artifact@v3
                with:
                    name: build-output
                    path: artifacts/main/Ayasuna.Frostseek/lib/
                    if-no-files-found: error
                    retention-days: 3
    publish:
        runs-on: ubuntu-latest
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        needs:
            - build
        steps:
            -   name: Setup .NET
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}
            -   name: Download build output
                uses: actions/download-artifact@v3
                with:
                    name: build-output
                    path: output
            -   name: Publish
                run: dotnet nuget push "output/Ayasuna.Frostseek.$GITHUB_REF_NAME.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$AYASUNA_NUGET_ORG_API_TOKEN"
                env:
                    AYASUNA_NUGET_ORG_API_TOKEN: ${{ secrets.AYASUNA_NUGET_ORG_API_TOKEN }}